### ISSUE TITLE
Never got a proper fit and I get 'asteca.plot' has no attribute 'get_isochrone' error

### ISSUE THREAD

**Issue by sivdur** [asteca/ASteCA#563]
Dear asteca team, 

I work on colab and installed asteca v 0.5.8.
![Image](https://github.com/user-attachments/assets/f70e7dc6-6b13-45b3-a165-2d6a755d930a)

I want to estimate the fundamental parameters of a cluster. To determine the prior parameters, I fitted a PARSEC isochrone by eye.
![Image](https://github.com/user-attachments/assets/31942eed-6056-4ef6-845b-4535f785b451)

Here are the parameters
```
OC_met = 0.1
OC_logAge = 8.5
OC_Av = 3.3
OC_distmod = 12.6
dmet = 0.2
dAge = 1
dmu = 4
dAv = 2
```

so I set the priors as follows:

```
priors = pyabc.Distribution(
    {
        "met": pyabc.RV("uniform", OC_met-dmet, 2*dmet),
        "loga": pyabc.RV("uniform", OC_logAge-dAge, 2*dAge),
        "dm": pyabc.RV("uniform", OC_distmod-dmu, 2*dmu),
        "Av": pyabc.RV("uniform", OC_Av-dAv, 2*dAv)
    }
)
```

but I can't get a proper solution. No matter what I do, the final minimized distance remains too high

`Final minimized distance: 88.81 (8881%)
`
![Image](https://github.com/user-attachments/assets/6985b347-24d6-4663-b936-a1626d0b2e31)

and I also get 
`AttributeError: module 'asteca.plot' has no attribute 'get_isochrone'
`
![Image](https://github.com/user-attachments/assets/0e67d2d1-5a74-4e9f-8e4c-8a6f649eefc5)

Here is my colab link: https://colab.research.google.com/drive/1Vu1FWvMbsg0WUHCkd8JPdtiWAs5ssbG2?usp=sharing

**Comment by Gabriel-p** [comment]
Hi @sivdur, I don't have access to the notebook since it's not public.

What I can tell you from what you share is that you are probably following the [example notebook in the docs](https://asteca.readthedocs.io/en/latest/tutorials/paramfit.html) Notice that this example is meant for the newest version of ASteCA which is 0.5.9, Sadly, this latest vresion probably won't install in Google Colab because Colab uses very old Python packages.

You can fix this in your notebook replacing the `distance` function with:

```
max_lkl = likelihood.max_lkl

def distance(synth_dict, _):
    """The likelihood is maximized for better fitted models but the pyABC
    distance requires minimization. Hence we normalize and invert.
    """
    lkl = likelihood.get(synth_dict["data"])
    return 1 - lkl / max_lkl
```

Also notice that the prior ranges might be a little too large (mainly the distance modulus where you use a range of 8) and the time spent processing with pyABC is too low (approx 1m30s), you could try increasing the number of populations.

The error you get when trying to plot comes from an issue in the documentation. To fix it (again, this is for the old 0.5.8 version you are using), use:

```
ax = plt.subplot(111)

asteca.plot.synthetic(synthcl, ax, fit_params, 0, True)
plt.show()
```

where the `0` means "use the first color defined" (the only color defined in your case), and `True` means "plot the isochrone along with the synthetic cluster".

Let me know if this helps.

**Comment by sivdur** [comment]
I remove the restrictions of the link. Yes, colab uses Python 3.11.11 which doesn't support asteca 0.5.9 
Here is the code I use


```
# best possible values for the cluster
OC_met = 0.1
OC_logAge = 8.5
OC_Av = 3.3
OC_distmod = 12.6
dmet = 0.2
dAge = 0.5
dmu = 2
dAv = 1

def model(fit_params):
    """Generate synthetic cluster. pyABC expects a dictionary from this
    function, so we return a dictionary with a single element.
    """
    synth_clust = synthcl.generate(fit_params)
    synth_dict = {"data": synth_clust}
    return synth_dict

priors = pyabc.Distribution(
    {
        "met": pyabc.RV("uniform", OC_met-dmet, 2*dmet),
        "loga": pyabc.RV("uniform", OC_logAge-dAge, 2*dAge),
        "dm": pyabc.RV("uniform", OC_distmod-dmu, 2*dmu),
        "Av": pyabc.RV("uniform", OC_Av-dAv, 2*dAv)
    }
)

def distance(synth_dict, _):
    """The likelihood is maximized for better fitted models but the pyABC
    distance requires minimization. Hence we normalize and invert.
    """
    max_lkl = likelihood.max_lkl
    lkl = likelihood.get(synth_dict["data"])
    return 1 - lkl / max_lkl

pop_size = 100
abc = pyabc.ABCSMC(
    model,
    priors,
    distance,
    population_size=pop_size
)

db_path = "sqlite:///" + os.path.join(tempfile.gettempdir(), "pyABC.db")
abc.new(db_path)

history = abc.run(minimum_epsilon=0.01, max_nr_populations=10)
``` 

Here are the results:

![Image](https://github.com/user-attachments/assets/3ceecaa6-40f0-4b75-a1bc-7973dbcdd170)

![Image](https://github.com/user-attachments/assets/f647b923-7814-46e2-a88c-ba1ad6cf1137)

![Image](https://github.com/user-attachments/assets/5416543b-bc86-4d85-839c-a3427e9d36c7)

![Image](https://github.com/user-attachments/assets/8c57af87-2371-465b-a63c-f2442694d085)

**Comment by Gabriel-p** [comment]
Try increasing the `max_nr_populations` parameter:

```
history = abc.run(minimum_epsilon=0.01, max_nr_populations=50)
```

**Comment by Gabriel-p** [comment]
Did that work for you @sivdur? If so consider closing the issue, thank you!

**Comment by sivdur** [comment]
It takes too long, and the distance percent doesn't decrease properly—simulation sampling remains poor. I think the issue is the number of cluster members. When the member count is below 50, the simulation predictions become weaker, causing the parameter distributions to show multiple peaks. 

Here are the samples:

![Image](https://github.com/user-attachments/assets/6fd849f0-fbda-40f6-b611-9b06cd4ce1f6)

Here is the isochrone fit:

![Image](https://github.com/user-attachments/assets/c41f1bb9-1d93-45eb-b7ea-8fc4ec49fb38)

the turn-off point seems to be not well-fitted.
Yes, you can close the issue. Thanks a lot.

**Comment by Gabriel-p** [comment]
Remember ASteCA does not fit isochrones, it fits synthetic clusters to you observed data. The exact path that the isochrones traces in the CMD can differ somewhat from the observed positions of the stars.

Yes, the fewer number of observed stars the fit will be more difficult and the uncertainty ranges will most likely be larger. When you have such low number of stars, fitting the metallicity is almost impossible (it is difficult enough with a large number of stars) so I'd recommend setting it to solar values and fit the other parameters.

This is not a simple Gaussian distribution that you are fitting with emcee, the distribution of the parameters will most likely never look normal. The results you show look perfectly reasonable to me.

Cheers
